---
title: "Investigative Question (Prompt 2) -  EDS214 Group Project"
format: html
authors: "Fouragers: Eva Newby, Jordan Sibley, Amanda Overbye, Marina Kochuten"
editor: visual
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
  message: false
---

Load packages

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
```

Read in data

```{r}
bisley_q1_raw <- read_csv(file.path("/courses/EDS214/group_project/2024/fouragers/data", "QuebradaCuenca1-Bisley.csv"))

bisley_q2_raw <- read_csv(file.path("/courses/EDS214/group_project/2024/fouragers/data", "QuebradaCuenca2-Bisley.csv"))

bisley_q3_raw <- read_csv(file.path("/courses/EDS214/group_project/2024/fouragers/data", "QuebradaCuenca3-Bisley.csv"))

prm_raw <- read_csv(file.path("/courses/EDS214/group_project/2024/fouragers/data", "RioMameyesPuenteRoto.csv"))
```

Clean up that data!

```{r}
bisley_q1_clean <- bisley_q1_raw %>% 
  clean_names() %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  filter(year %in% (1988:1990)) %>%
  select(sample_date, sample_id, year, na) # change variables to account for sodium

bisley_q2_clean <- bisley_q2_raw %>% 
  clean_names() %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
filter(year %in% (1988:1990)) %>%
  select(sample_date, sample_id, year, na)

bisley_q3_clean <- bisley_q3_raw %>% 
  clean_names() %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  filter(year %in% (1988:1990)) %>%
  select(sample_date, sample_id, year, na)

prm_clean <- prm_raw %>% 
  clean_names() %>% 
  mutate(year = lubridate::year(sample_date)) %>% 
  filter(year %in% (1988:1990)) %>%
  select(sample_date, sample_id, year, na)

```

Full join of all 4 data sets

```{r}
stream_chem <- bisley_q1_clean %>% 
  full_join(bisley_q2_clean) %>% 
  full_join(bisley_q3_clean) %>% 
  full_join(prm_clean)
```

Create our plot

```{r}

saltplot_g4 <- ggplot(data = stream_chem, aes(x = sample_date, y = na, color = sample_id)) +
  geom_line()+
  geom_vline(xintercept = as.numeric(stream_chem$sample_date[119]), linetype = "dashed", color = "black")+
  labs(x = "Sample Date (YYYY-MM)", 
       y = "Sodium (mg/L)", 
       title = "Are Stream Salt Amounts Affected by Hurricane Hugo?",
       color = "Sample Name and Altitude")+
   scale_y_continuous(breaks = seq(0,15, by = 3))+
  scale_x_date(limits = c(as.Date("1988-01-01"), as.Date("1990-12-31")),
                     expand = c(0,0))+
  annotate("text", x = c(as.Date("1989-12-19")), y = 14, label = "Hurricane Hugo", color = "black")+
 scale_color_manual(values = c("#22333b", "blue", "#fad643", "#1c7c54"),
                     labels = c("PRM, 140 m amsl", "BQ1, 218 m amsl","BQ3, 198 m amsl","BQ2, 218 m amsl")) +
  theme(legend.position = c(0.11, 0.85),
        panel.background = element_blank(),
        panel.grid.major = element_line(color = "lightgray"),
        axis.ticks = element_line(color = "lightgray"))

```

Based on the plot, it appears that sodium amounts in the streams measured across altitudes were not affected by Hurricane Hugo. More statistical investigation is needed to make an official determination.
